### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by rjleveque**
Same as other repos.

### CODE REVIEW

**Comment by mandli** [comment]
I think we should require this repo to actually have a license in each sub-directory to leave it open to  other contributors to determine the license.

**Comment by rjleveque** [comment]
Since we haven't had other contributors so far, I think it's simpler to leave it as BSD for this entire repo.  If other people have apps they want to license differently, they will probably also have their own repository and won't want to contribute it to the `apps` repository anyway.

Somewhere in the docs we should add a list of pointers to repos for other applications that have used Clawpack, but that are not included here.  There are already several repos associated with publications, for example.  

But I'm open to other opinions.  At one point we talked about using submodules to allow others to easily include their applications in here, but I don't think most people would consider this easier than just sending us a link to their own repo for inclusion in our docs.

**Comment by mandli** [comment]
I am a little worried that by providing a license at the top of the repository though that it would confuse (or be looked upon as superseding) the contained code.  I think at the very least we should put a note that the general license is BSD unless otherwise stated in a containing directory (I think this is allowed).

**Comment by rjleveque** [comment]
That sounds like a good compromise.

**Comment by mandli** [comment]
Added.

**Pull request merged**
