### PR TITLE
Bypassing 'Permission denied' errors'  while fetching submodules

### PR DESCRIPTION
**Pull request by Dirivian**
The README is modified to suggest adding ssh keys to avoid 'Permission denied' errors encountered when using HTTPS urls.

### CODE REVIEW

**Comment by mandli** [comment]
Can you add an additional comment to the "one liner" mentioning you need to run that from `$CLAW` rather than inside of the `apps` repository?

**Comment by Dirivian** [comment]
I reran the two commands from within the `apps` repository. 

By one-liner, do you mean the commit message or the modification to the README file ?

**Comment by mandli** [comment]
I meant the command including the `recursive` command.

**Comment by Dirivian** [comment]
I added a few more lines to explain it in a bit more detail. Does this seem enough/alright ?

**Comment by rjleveque** [comment]
I think if you clone recursively then you don't need to do the submodule init and update, that's only if you already have the `apps` repository and want to get the submodules?

I don't understand why using the `https` address gives permission errors? If you have an ssh key set up then you might be able to clone `git@github.com:clawpack/apps.git`, but I didn't think ssh keys are used at all when using `https`?

At any rate it seems like users should be able to clone without needing ssh keys at all.

@mandli: I think one problem is that `apps/.gitmodules` contains an `ssh` address for one of the two submodules.  Can you fix this and test?

**Comment by rjleveque** [comment]
I suggest #86 instead.

**Pull request closed without merging**
