### PR TITLE
[WIP] V5.3.0 updates

### PR DESCRIPTION
**Pull request by rjleveque**
There are probably more apps that need updating.

This fixes problem seen by @donnaaboise

### CODE REVIEW

**Comment by mandli** [comment]
We should make a checklist.  Here's a start on one:
 - [ ] Tsunami
    * [x] bowl_radial_fgmax
    * [x] chile2010_fgmax
    * [ ] radial-ocean
 - [ ] Storm surge
    * [ ] Ike
    * [ ] Sandy
    * [ ] Irene
    * [ ] Katrina
 - [ ] Euler - Shockbubble
 - [ ] FVM Book
     * [ ] Lots

**Comment by donnacalhoun** [comment]
I can add the Tohoku (HAI1123) example.  In any case,  I'll push a "ge_tohoku" branch to the apps repo.   I am setting this up for a student, and this seems like the logical place to put it.

**Comment by rjleveque** [comment]
@mandli: This might be ready to merge?

**Comment by mandli** [comment]
Did the Euler shock-bubble and radial ocean examples get changed or should we just go ahead?

**Comment by rjleveque** [comment]
- `tsunami/radial_ocean` is not yet in `master`.

- `euler/shockbuuble/2d_axisym` is fixed.

- `euler/shockbuuble/3d/`: I fixed the Makefile and added gauges to `setrun.py` and `setplot.py` but it  currently dies with the error below, and the gauges don't look right up to the time it dies.
```
 AMRCLAW: level  1  CFL = .105E+01  dt = 0.9106E-02  final t = 0.526946E+00
 *** a**2 <= 0 in y-sweep at           26
 stopped with a**2 < 0...

```

**Comment by mandli** [comment]
Eh, sounds like we should merge and not worry about it.

**Pull request merged**
