### PR TITLE
Pyclaw notebook updates

### PR DESCRIPTION
**Pull request by ketch**
Two new notebooks: one deals purely with geometry classes; the other shows shallow water diffractons. 
 Gisted, executed versions of the notebooks are here:

- https://gist.github.com/ketch/1a7888d1fcc37209b260
- http://nbviewer.jupyter.org/gist/ketch/9250942

### CODE REVIEW

**Comment by mandli** [comment]
Looks great except the geometry notebook is not Python 3 compatible.

**Comment by ketch** [comment]
Ack; how did I miss that?

Thanks for checking.  I've fixed it.

**Comment by mandli** [comment]
No problem.  One thing that may be worth thinking about for some of these is to setup a test for these via nbconvert  (although the geometry example would not work still).

**Comment by ketch** [comment]
Yeah, I have that set up for the Riemann book where it checks that all notebooks at least run without errors.  I will set it up here when I find time.

**Comment by mandli** [comment]
I have it setup for my lecture notes following what you did for the Riemann book so I can try to get to it as well.

**Pull request merged**
