### PR TITLE
[WIP] Update notebooks to Jupyter and to work with Plotly 1.x.

### PR DESCRIPTION
**Pull request by ketch**
This is intended to replace https://github.com/clawpack/apps/pull/67.  The notebooks are in Jupyter format and the Plotly code that was originally written to the Plotly 0.5 API is now updated to the Plotly 1.x API.

However, I am having trouble now with the visclaw plotting code, for instance at the end of quadrants.ipynb.  The cell with this code:

```
from clawpack.visclaw import data
from clawpack.visclaw import frametools
plotdata = data.ClawPlotData()
plotdata.setplot = claw.setplot
claw.plotdata = frametools.call_setplot(claw.setplot,plotdata)

frame = claw.load_frame(40)
f=claw.plot_frame(frame)
```

Produces no plot and emits the warning `*** WARNING:  No setplot specified!`.  @rjleveque or @mandli , do you know what changed to cause this?

### CODE REVIEW

**Comment by mandli** [comment]
I have no idea why that would happen.  Is this the preferred way to plot from a notebook though?

**Comment by rjleveque** [comment]
Why do these lines use `claw.setplot`, which seems to be initialized to `None`?

```
plotdata.setplot = claw.setplot
claw.plotdata = frametools.call_setplot(claw.setplot,plotdata)
```

If I just change these to `setplot` (which was defined in the previous cell), it works fine.

Also, where you note that the `plotly` cell only works if you have an account, you might also mention that `plotly` must be installed locally as well.  I assume it's in `anaconda` but I used brew/pip on my new laptop and didn't have it until doing `pip install plotly`.

**Comment by ketch** [comment]
Whoops!  Sorry, I should have looked closer.  I must have inadvertently broken this long ago.  It's all fixed now, and I added the instructions to install plotly.  Thanks!

**Comment by rjleveque** [comment]
Thanks!

**Pull request merged**
